MODEL:
  DEVICE: 'cuda'
  NAME: 'resnet50'
  LAST_STRIDE: 1
  PRETRAIN_PATH: '../weights/lup_moco_r50.pth'
  PRETRAIN_CHOICE: 'luperson'
  NECK: 'bnneck'
  IF_WITH_CENTER: 'no'
  METRIC_LOSS_TYPE: 'XE-tri-mg'
  IF_LABELSMOOTH: 'on'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  FLIP_PROB: 0.5
  RE_PROB: 0.5
  PIXEL_MEAN: [0.3525, 0.3106, 0.3140] # LUPerson mean
  PIXEL_STD: [0.2660, 0.2522, 0.2505] # LUPerson std
  PADDING: 10
  RCD_PROB: 0.6
  CJ_PROB: 0.

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: '../'

DATALOADER:
  NUM_WORKERS: 2
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  CLUSTER_MARGIN: 0.3
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
  RANGE_K: 2
  RANGE_MARGIN: 0.3
  MARGIN: 0.1
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 128
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 160
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'yes'
  WEIGHT: "../official_outputs/Market1501/Augmentation/t11_base_margin0.1_smooth_rcd0.6/resnet50_checkpoint_10680.pt"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  WITH_CENTROIDS: 'yes'

OUTPUT_DIR: ""